---
termserver_version: latest
environment_shortname: UNKNOWN
mysql_service: mysql
#Set the db content from a backup
set_db_content:  True
# Force the import to download a fresh copy of the  backup zip and use that.
force_zip_download:  False
# Dir where term server is installed
term_serv_dir: /opt/termserver
# Dir name where indexes go
term_serv_indexes_dir: "indexes"
# Dir name where resources go
term_serv_resources_dir: "resources"
# Dir name where resources go
term_serv_index_dir: "termserver_indexes"
# Dir name where templates go
term_serv_template_dir: "template-store"
#Term Serv Resources dir
term_serv_dir_resources: "{{term_serv_dir}}/{{ term_serv_resources_dir }}"
#Term Serv Indexes dir
term_serv_dir_resources_indexes: "{{term_serv_dir_resources}}/{{ term_serv_indexes_dir }}"

#Import
# The SQL import file name
import_term_serv_sql_name: "snomedStore.sql"
# The base Dir for the import data
import_term_serv_base_dir: /opt/data/termserver

#The base URL where the backup zip file should be downloaded from
#import_zip_base_url: "https://s3.amazonaws.com/prod-term.backup.ihtsdo/"
#import_zip_base_url: "http://192.168.0.2/"
#import_zip_base_url: "https://s3.amazonaws.com/ts-sql.ihtsdo/"

#import_zip_base_url: "https://s3.amazonaws.com/prod-term.backup.ihtsdo/"

#The import file filname (also the folder name when zip is unzipped)
#import_term_serv_filename:  ""
#import_zip_base_url: ""

#The import filname with file ending
import_term_serv_file: "{{ import_term_serv_filename }}.zip"
# The directory where the unzipped data is to be found
import_term_serv_data_dir: "{{import_term_serv_base_dir}}/{{ import_term_serv_filename }}"
#The import zip URL
import_zip_url: "{{import_zip_base_url}}{{ import_term_serv_file }}"
#The path to the import zip file
import_zip_file: "{{import_term_serv_base_dir}}/{{import_term_serv_file}}"
# The path to the import indexes folder
import_term_serv_dataset: "{{import_term_serv_data_dir}}/dataset"
# The path to the sql import file
import_term_serv_sql: "{{import_term_serv_dataset}}/{{ import_term_serv_sql_name }}"
# The path to the import indexes folder
import_term_serv_indexes: "{{import_term_serv_dataset}}/{{ term_serv_index_dir }}"
# The path to the import resources folder
import_term_serv_resources: "{{import_term_serv_dataset}}/{{ term_serv_resources_dir }}"
# The path to the import templates folder
import_term_serv_templates: "{{import_term_serv_dataset}}/{{ term_serv_template_dir }}"


#target dir for term_serv_indexes
target_term_serv_indexes: "/opt/{{ term_serv_index_dir }}"
#target dir for term_serv_templates
target_term_serv_templates: "/opt/snomed-template-service/"

traceability_database: traceability

script_dir: /opt/scripts/restore_term
new_restore_script: term_mysql_restore.sh
restore_cmd: "{{ script_dir }}/{{ new_restore_script }}"
restore_log: "{{ script_dir }}/restore_{{ ansible_date_time.iso8601 }}.log"
full_restore_cmd: "{{ restore_cmd }} >> {{ restore_log }}"

